### ISSUE TITLE
seeRemoteServiceReceived expectation matched correctly but not A::postRequest()->andUrl(Is::equalTo(...

### ISSUE THREAD

**Issue by thitami** [mcustiel/phiremock-codeception-extension#2] opened 2016-12-13 15:49 UTC
Hello,

I have got the following issue using the codeception extension.

Although the expectation that the following generates, it is matched and asserted successfully: 
```php
$I->seeRemoteServiceReceived(
            1,
            A::postRequest()->andUrl(Is::equalTo('/v1/test/users/invite'))
        );
```

this expectation never gets matched and am wondering if we have got an uncaught bug here?
```
Mcustiel\Phiremock\Domain\Expectation::__set_state(array(    'request' =>    Mcustiel\Phiremock\Domain\Request::__set_state(array(      'method' => 'post',      'url' =>      Mcustiel\Phiremock\Domain\Condition::__set_state(array(        'matcher' => 'isEqualTo',        'value' => '/v1/test/users/invite',     )),      'body' =>      Mcustiel\Phiremock\Domain\Condition::__set_state(array(        'matcher' => 'isEqualTo',        'value' => '{"software_system_id":1,"client_reference":"1_1","email_address":"test@test.code","unique_reference":6655,"title":"Mr","forename":"Sam","surname":"Smith","full_name":"Mr Sam Smith","link":false}',     )),      'headers' =>      array (       'Content-Type' =>        Mcustiel\Phiremock\Domain\Condition::__set_state(array(          'matcher' => 'isEqualTo',          'value' => 'application/json',       )),       'ApplicationBearer' =>        Mcustiel\Phiremock\Domain\Condition::__set_state(array(          'matcher' => 'isEqualTo',          'value' => '12345',       )),     ),   )),    'response' =>    Mcustiel\Phiremock\Domain\Response::__set_state(array(      'statusCode' => 200,      'body' => '{"success":true}',      'headers' =>      array (       'Content-Type' => 'application/json',     ),      'delayMillis' => NULL,   )),    'proxyTo' => NULL,    'scenarioName' => NULL,    'scenarioStateIs' => NULL,    'newScenarioState' => NULL,    'priority' => 0, ))
```

My request as copied from the phiremock logs is:
```
POST: http://localhost/v1/test/users/invite || {"software_system_id":1,"client_reference":"1_1","email_address":"test@test.code","unique_reference":6655,"title":"Mr","forename":"Sam","surname":"Smith","full_name":"Mr Sam Smith","link":false}
```

I am creating the expectation as such (please notice the headers):

```php
 $phiremock = new Phiremock('127.0.0.1', '8088');
        $expectation = Phiremock::on(
            A::postRequest()->andUrl(Is::equalTo('/v1/test/users/invite'))
                ->andBody(
                    Is::equalTo(
                        json_encode(
                            array(
                                'software_system_id' => 1,
                                'client_reference' => '1_1',
                                'email_address' => DEFAULT_EMAIL_ADDRESS,
                                'unique_reference' => $expectedContactID,
                                'title' => DEFAULT_PERSON_TITLE,
                                'forename' => DEFAULT_PERSON_FORENAME,
                                'surname' => DEFAULT_PERSON_SURNAME,
                                'full_name' => DEFAULT_PERSON_TITLE.' '.DEFAULT_PERSON_FORENAME.' '.DEFAULT_PERSON_SURNAME,
                                'link' => false,
                            )
                        )
                    )
                )
                ->andHeader('Content-Type', Is::equalTo('application/json'))
                ->andHeader(
                    'ApplicationBearer',
                    //TODO
                    Is::equalTo('12345')
                )
        )->then(
            $respond->andBody(json_encode(array('success' => $success)))
                ->andHeader('Content-Type', 'application/json')
        );
        $phiremock->createExpectation($expectation);
```

My only assumptions at the moment, are either the port that I am sending the request to, is ignored or something is wrong with the headers.

Maybe @mcustiel could share his thoughts?

**Comment by mcustiel** [comment] 2016-12-13 15:56
Hi, Thitami.
Thank you for reporting this.
Jus to discard a copy paste issue, could you check why the URL in the expectation and the one in the logs are different?
`/v1/test/users/invite` vs `v1/eproperty/users/invite`

Thank you.

**Comment by thitami** [comment] 2016-12-13 16:02
Hi @mcustiel and thank you alot for the prompt response.

Just updated my post; just forgot to edit the url for all the references while writing the post. :)

**Comment by mcustiel** [comment] 2016-12-13 16:06
Great. Will give it a look in the next days. Thank you very much.

**Comment by thitami** [comment] 2016-12-13 16:07
Thanks, @mcustiel !

**Comment by mcustiel** [comment] 2016-12-14 11:43
Hi, @thitami.
I can not reproduce the behaviour you describe. I share with you my Codeception's Cest file so you can check if it matches your situation or it needs to be tuned. Thank you.

```php
<?php

use Mcustiel\Phiremock\Client\Phiremock as PhiremockClient;
use Mcustiel\Phiremock\Client\Utils\A;
use Mcustiel\Phiremock\Client\Utils\Is;
use Mcustiel\Phiremock\Client\Utils\Respond;
use Mcustiel\Phiremock\Client\Phiremock;

class ReportedIssuesCest
{
    const DEFAULT_PERSON_TITLE = 'Mr';
    const DEFAULT_PERSON_FORENAME = 'Sam';
    const DEFAULT_PERSON_SURNAME = 'Smith';
    const DEFAULT_EMAIL_ADDRESS = 'test@test.code';

    /**
     * @var \Mcustiel\Phiremock\Client\Phiremock
     */
    private $phiremock;

    public function _before(AcceptanceTester $I)
    {
        $I->sendDELETE('/__phiremock/expectations');
        $this->phiremock = new PhiremockClient('127.0.0.1', '8086');
    }

    public function testIssueNumber2(AcceptanceTester $I)
    {
        $expectedContactID = 6655;
        $success = true;
        $request = A::postRequest()
            ->andUrl(Is::equalTo('/v1/test/users/invite'))
            ->andBody(
                Is::equalTo(
                    json_encode(
                        array(
                            'software_system_id' => 1,
                            'client_reference' => '1_1',
                            'email_address' => self::DEFAULT_EMAIL_ADDRESS,
                            'unique_reference' => $expectedContactID,
                            'title' => self::DEFAULT_PERSON_TITLE,
                            'forename' => self::DEFAULT_PERSON_FORENAME,
                            'surname' => self::DEFAULT_PERSON_SURNAME,
                            'full_name' => self::DEFAULT_PERSON_TITLE
                                . ' ' . self::DEFAULT_PERSON_FORENAME
                                . ' ' . self::DEFAULT_PERSON_SURNAME,
                            'link' => false
                        )
                    )
                )
            )
            ->andHeader('Content-Type', Is::equalTo('application/json'))
            ->andHeader(
                'ApplicationBearer',
                // TODO
                Is::equalTo('12345')
            );
        $expectation = Phiremock::on($request)
        ->then(Respond::withStatusCode(200)
            ->andBody(
                json_encode(array('success' => $success))
            )
            ->andHeader('Content-Type', 'application/json')
        );
        $this->phiremock->createExpectation($expectation);

        $I->haveHttpHeader('Content-Type', 'application/json');
        $I->haveHttpHeader('ApplicationBearer', '12345');
        $I->sendPOST(
            '/v1/test/users/invite',
            '{"software_system_id":1,"client_reference":"1_1","email_address":"test@test.code","unique_reference":6655,"title":"Mr","forename":"Sam","surname":"Smith","full_name":"Mr Sam Smith","link":false}'
        );

        $I->seeResponseCodeIs('200');
        $I->seeResponseContains('{"success":true}');
        $I->assertEquals(1, $this->phiremock->countExecutions($request));
    }
}
```

**Comment by thitami** [comment] 2016-12-14 11:49
Thanks for taking the time for that, @mcustiel.
So, that means that all go smoothly for you on the above code and all assertions are accomplished?

**Comment by thitami** [comment] 2016-12-14 11:56
Great. I am having a look into my logs and implementation to see if I missed anything obvious.

**Comment by mcustiel** [comment] 2016-12-14 12:01
Try calling `$I->expectARequestToRemoteServiceWithAResponse($expectation)` instead of using the client directly. Maybe there's some mixing with the ports.

**Comment by thitami** [comment] 2016-12-14 15:07
This one is working good (`$I->expectARequestToRemoteServiceWithAResponse($expectation)`) 👍.

**Comment by mcustiel** [comment] 2016-12-14 15:13
Great. Probably the client was not pointing to the same server and port that codeception was pointing to. Will close the issue. Than you very much.

**Closed** 2016-12-14 15:16 UTC
Labels: invalid

**Comment by thitami** [comment] 2016-12-14 15:18
I am wondering whether the fact that the port is missing from my logs request could indicate an issue: 

`
[2016-12-14 15:17:21] stdoutLogger.DEBUG: Searching matching expectation for request [] []
[2016-12-14 15:17:21] stdoutLogger.INFO: Request received: POST: http://localhost/v1/eproperty/users/invite || {"software_system_id":1,"client_reference":"1_1","email_address":"existingapplicant2@test.com","unique_reference":6702,"title":"MR","forename":"Mr ExistingApplicantForename ExistingApplicantSurname","surname":"ExistingApplicantSurname ExistingApplicantForename Mr","full_name":"MR Mr ExistingApplicantForename ExistingApplicantSurname ExistingApplicantSurname ExistingApplicantForename Mr","link":false} [] []
[2016-12-14 15:17:21] stdoutLogger.DEBUG: Checking if request matches an expectation [] []
[2016-12-14 15:17:21] stdoutLogger.DEBUG: Checking Method against expectation [] []
[2016-12-14 15:17:21] stdoutLogger.DEBUG: Checking Url against expectation [] []
[2016-12-14 15:17:21] stdoutLogger.DEBUG: Checking Body against expectation [] []
[2016-12-14 15:17:21] stdoutLogger.DEBUG: Processing took 2.043 milliseconds [] []`

**Comment by mcustiel** [comment] 2016-12-14 15:21
Hey. Don't worry. That is just PSR-7 implementation's toString magic method. Phiremock does not use the host part in the url at all, so it is always localhost by default. The toString method prints the full URL, so the localhost part is displayed, but phiremock ignores it.

**Comment by thitami** [comment] 2016-12-14 15:27
Right, cool. Thanks for the clarification. 🙂

**Comment by thitami** [comment] 2016-12-15 09:41
Sorry for reopening this @mcustiel. Just realised that I am using ApiTester and not AcceptanceTester,

with this config: `class_name: ApiTester
modules:
    enabled:
        - \Helper\Api
        - REST:
                url: http://localhost:8000/v1
                depends: PhpBrowser
                part: JSON
        - Db:
                dsn: ''
                user: ''
                password: ''
                dump: 'tests/_data/dump.sql'
                populate: false
                cleanup: true
                reconnect: true
        - Phiremock:
                host: 127.0.0.1
                port: 8088`

On top of that `$I->assertEquals()` does not seem to be available in my end: `[RuntimeException] Call to undefined method ApiTester::assertEquals
`

**Comment by mcustiel** [comment] 2016-12-15 13:02
Hey. To get `assertEquals` method I think you need to add Asserts module in your suite's configuration yaml, but phiremock does not needs it.
Regarding the exception, I will release a new tag with a fix for it.

**Comment by thitami** [comment] 2016-12-15 13:54
Nice one.
Thanks alot for the reply and looking forward to use your fix 👍

**Comment by mcustiel** [comment] 2016-12-15 13:59
Hi. You can already run composer update and get v1.2.2 with the fix.

**Comment by thitami** [comment] 2016-12-15 14:06
Hi Mariano,
Just ran `composer update` and got v1.2.2; this is the stack trace:

`Symfony\Component\Process\Exception\LogicException]
  Can not send signal on a non running process.


Exception trace:
 () at /private/var/www/jupix-api/vendor/symfony/process/Process.php:1446
 Symfony\Component\Process\Process->doSignal() at /private/var/www/jupix-api/vendor/symfony/process/Process.php:400
 Symfony\Component\Process\Process->signal() at /private/var/www/jupix-api/vendor/mcustiel/phiremock-codeception-extension/src/Extension/PhiremockProcess.php:76
 Codeception\Extension\PhiremockProcess->stop() at /private/var/www/jupix-api/vendor/mcustiel/phiremock-codeception-extension/src/Extension/Phiremock.php:95
 Codeception\Extension\Phiremock->stopProcess() at n/a:n/a
 call_user_func() at /private/var/www/jupix-api/vendor/symfony/event-dispatcher/EventDispatcher.php:184
 Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() at /private/var/www/jupix-api/vendor/symfony/event-dispatcher/EventDispatcher.php:46`

**Comment by mcustiel** [comment] 2016-12-15 14:14
Damn. That will be difficult to solve, because I don't have the error anymore. This is my log:
```
:~/workspace/php/phiremock-codeception-extension$ ./vendor/bin/codecept run -c tests
Codeception PHP Testing Framework v2.2.7
Powered by PHPUnit 5.7.4-9-g94cec03 by Sebastian Bergmann and contributors.

Acceptance Tests (1) ---------------------------------------------------------
✔ BasicTestCest: Try to test (0.09s)
------------------------------------------------------------------------------

Unit Tests (0) ---------------------------------------------------------------
------------------------------------------------------------------------------

Functional Tests (0) ---------------------------------------------------------
------------------------------------------------------------------------------


Time: 3.88 seconds, Memory: 10.00MB

OK (1 test, 1 assertion)
```
Will give it a deep look when I have more time.

Thanks for reporting.

**Comment by mcustiel** [comment] 2016-12-15 14:31
Could you check if you have a phiremock process running in background? It happened to me while fixing the bug. `ps aux | grep phiremock`. If there's one, kill it and run the tests again.

**Comment by thitami** [comment] 2016-12-15 15:37
Just checked with `ps aux | grep phiremock` and the process is running once.
